/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/public/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/companies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/companies/{slug}/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicVehicles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/companies/{slug}/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicVehicle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/companies/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/companies/{slug}/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPublicReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/reservations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicCompanyBranding: {
            primaryColor?: string;
            logoUrl?: string | null;
        };
        PublicCompany: {
            id?: string;
            slug?: string;
            name?: string;
            description?: string | null;
            location?: string | null;
            locationSlug?: string | null;
            city?: string | null;
            citySlug?: string | null;
            latitude?: number | null;
            longitude?: number | null;
            vehicleCount?: number | null;
            fleetSize?: number | null;
            isPublic?: boolean;
            defaultLocale?: string;
            currency?: string;
            branding?: components["schemas"]["PublicCompanyBranding"];
        };
        PublicCompanyPage: {
            data?: components["schemas"]["PublicCompany"][];
            page?: components["schemas"]["Page"];
        };
        PublicPhoto: {
            url?: string;
            src?: string;
            href?: string;
            photoUrl?: string;
        };
        PublicVehicle: {
            id?: string;
            companySlug?: string;
            companyName?: string;
            make?: string;
            brand?: string;
            model?: string;
            year?: number;
            color?: string;
            fuelType?: string;
            fuel?: string;
            category?: string;
            type?: string;
            dailyRate?: number;
            pricePerDay?: number;
            deposit?: number;
            seats?: number | null;
            transmission?: string | null;
            description?: string | null;
            currency?: string;
            photos?: (string | components["schemas"]["PublicPhoto"])[] | null;
            photoUrl?: string | null;
            imageUrl?: string | null;
            available?: boolean;
            status?: string;
            isPublic?: boolean;
        };
        PublicVehiclePage: {
            data?: components["schemas"]["PublicVehicle"][];
            page?: components["schemas"]["Page"];
        };
        AvailabilityConflict: {
            startDate?: string;
            endDate?: string;
            reservationId?: string;
        };
        PublicAvailability: {
            vehicleId?: string;
            available?: boolean;
            unavailableDates?: string[];
            conflicts?: components["schemas"]["AvailabilityConflict"][];
        };
        PublicAvailabilityPage: {
            data?: components["schemas"]["PublicAvailability"][];
            page?: components["schemas"]["Page"];
        };
        CreateGuestReservation: {
            vehicleId: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            guestPhone: string;
        };
        PublicCustomer: {
            name?: string;
            email?: string;
            phone?: string;
            phoneNumber?: string;
        };
        PublicReservation: {
            id?: string;
            token?: string;
            status?: string;
            vehicleId?: string;
            startDate?: string;
            endDate?: string;
            totalPrice?: number;
            grandTotal?: number;
            totalAmount?: number;
            total?: number;
            currency?: string;
            guestName?: string;
            guestEmail?: string;
            guestPhone?: string;
            companySlug?: string;
            createdAt?: string;
            customer?: components["schemas"]["PublicCustomer"];
            vehicle?: components["schemas"]["PublicVehicle"];
            company?: components["schemas"]["PublicCompany"];
        };
        Page: {
            total?: number;
            nextCursor?: string | null;
        };
        FieldError: {
            field?: string;
            code?: string;
        };
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            code?: string;
            detail?: string;
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: {
        /** @description RFC 9457 problem details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPublicCompanies: {
        parameters: {
            query?: {
                q?: string;
                location?: string;
                from?: string;
                to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public companies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCompany"][] | components["schemas"]["PublicCompanyPage"] | null;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPublicCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCompany"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listPublicVehicles: {
        parameters: {
            query?: {
                q?: string;
                type?: string;
                category?: string;
                seats?: number;
                minSeats?: number;
                transmission?: string;
                from?: string;
                to?: string;
                sort?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public vehicles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicVehicle"][] | components["schemas"]["PublicVehiclePage"] | null;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPublicVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicVehicle"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPublicAvailability: {
        parameters: {
            query: {
                from: string;
                to: string;
                vehicleId?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Availability for a vehicle or fleet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAvailability"] | components["schemas"]["PublicAvailability"][] | components["schemas"]["PublicAvailabilityPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createPublicReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuestReservation"];
            };
        };
        responses: {
            /** @description Created reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReservation"];
                };
            };
            /** @description Created reservation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReservation"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPublicReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation by public token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicReservation"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
